# By: Oscar Andersson (github.com/oscarA1994)

FROM openvisualcloud/xeon-centos76-media-ffmpeg

# Setup for the moga software
RUN yum update -y
RUN yum install -y python3 python3-pip wget make git nano

# pip packages
RUN pip3 install numpy==1.18.1 \
                 pygmo==2.13.0 \
                 scikit-image==0.16.2 \
                 matplotlib==3.1.3 \
                 ffmpeg-python==0.2.0 \
                 requests==2.22.0 \
                 tqdm==4.43.0


