
version: "2.3"
services:
    moga-encode:
        container_name: moga-encode
        build:
            context: .
            dockerfile: Dockerfile
        image: oscar/moga-encode
        network_mode: "host"
        ipc: "host"
        volumes:
            - ./:/MOGA-Encode
        tmpfs:
            - /tmp
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        devices:
            - "/dev/dri:/dev/dri"
        working_dir: /MOGA-Encode
        stdin_open: true
        tty: true
        command: python3 moga.py

    moga-encode-av1:
        container_name: moga-encode-av1
        build:
            context: .
            dockerfile: Dockerfile-AV1
        image: oscar/moga-encode-av1
        network_mode: "host"
        ipc: "host"
        volumes:
            - ../MOGA-Encode:/MOGA-Encode
            - ./data:/data
            - ./output:/output
        tmpfs:
            - /tmp
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        devices:
            - "/dev/dri:/dev/dri"
        working_dir: /MOGA-Encode
        stdin_open: true
        tty: true
        command: python3 moga.py

    hrnet:
        container_name: hrnet
        build:
            context: ./ml_algs/HRNet
            dockerfile: Dockerfile
        image: oscar/hrnet
        network_mode: "host"
        ipc: "host"
        volumes:
            - ./data:/data
            - ./ml_algs/HRNet:/mll
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        working_dir: /ml
        stdin_open: true
        tty: true
        command: python tools/rest_communication.py

    gscnn:
        container_name: gscnn
        build:
            context: ./ml_algs/GSCNN
            dockerfile: Dockerfile
        image: oscar/gscnn
        network_mode: "host"
        ipc: "host"
        volumes:
            - ./data:/data
            - ./ml_algs/GSCNN:/mll
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        working_dir: /ml
        stdin_open: true
        tty: true


