
version: "2.3"
services:
    moga-encode:
        container_name: moga-encode
        build:
            context: .
            dockerfile: Dockerfile
        image: oscar/moga-encode
        network_mode: "host"
        ipc: "host"
        volumes:
            - ./:/MOGA-Encode
            - ../data:/data
            - ../output:/output
        tmpfs:
            - /tmp
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        devices:
            - "/dev/dri:/dev/dri"
        working_dir: /MOGA-Encode
        stdin_open: true
        tty: true
        command: python3 moga.py

    hrnet:
        container_name: hrnet
        build:
            context: ../HRNet
            dockerfile: Dockerfile
        image: oscar/hrnet
        network_mode: "host"
        ipc: "host"
        volumes:
            - ../data:/data
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        working_dir: /ml
        stdin_open: true
        tty: true
        command: python tools/rest_communication.py

    gscnn:
        container_name: gscnn
        build:
            context: ../GSCNN
            dockerfile: Dockerfile
        image: oscar/gscnn
        network_mode: "host"
        ipc: "host"
        volumes:
            - ../data:/data
            - ../GSCNN:/mll
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        working_dir: /ml
        stdin_open: true
        tty: true


